### ISSUE TITLE
no output 

### ISSUE THREAD

**Issue by MansHere** [codeshaunted/monke#13]
im am doing the following command  "monke unpack "C:\Users\olive\AppData\LocalLow\Ninja Kiwi\BloonsTD6-Epic\9adfd9ba7a484cf0a99a7904eddb12a9\link\PRODUCTION\current\Profile.Save" "C:\Users\olive\Pictures" 11"
and i am not getting an error nor any output please help thx :=)

**Comment by MansHere** [comment]
nv fixed monke unpack Profile.Save Profile.Save.json 11 worked

**Comment by MansHere** [comment]
i do have a question though i waht to just get a maxed save or summon what should i put in the json file for that

**Comment by Roshi617** [comment]
Try:

"monke unpack "C:\Users\olive\AppData\LocalLow\Ninja Kiwi\BloonsTD6-Epic\9adfd9ba7a484cf0a99a7904eddb12a9\link\PRODUCTION\current\Profile.Save" "C:\Users\olive\Pictures\Profile.save.json" 11"

**Comment by Roshi617** [comment]
Oops, I am unable to read apparently.

**Comment by codeshaunted** [comment]
It doesn’t currently output an error if it fails. I have a version with error messages on my laptop and will push it soon.
