### ISSUE TITLE
how do i use this

### ISSUE THREAD

**Issue by dropier** [codeshaunted/monke#14]
can someone give me a guide or something because all the readme says is that it has 2 commands, unpack and pack, and i've tried searching for the files of which i should use the program on but it's not on my btd6 steam folder

**Comment by dropier** [comment]
apparently its on appdata locallow but even then i found no save file on %appdata%\LocalLow\NinjaKiwi\BloonsTD6

**Comment by codeshaunted** [comment]
At least for the Steam edition of BTD6, your saves are actually contained
in Steam userdata. On Windows this would put them at C:\Program Files
(x86)\Steam\userdata\<your steam user id>\960090

**Comment by dropier** [comment]
thx bro
