### ISSUE TITLE
Passing a round after DoubleCashMode is true resets the save

### ISSUE THREAD

**Issue by Xioverze** [codeshaunted/monke#17]
The video that shows what im experiencing
https://streamable.com/sa1il5

**Comment by Xioverze** [comment]
on second thought i should try this with a non steam account save brb
still does the same thing, with purchasedDoubleCashMode being the only thing that changed

**Comment by codeshaunted** [comment]
This issue is outside of the scope of this project, the save file packing works; this is not a problem with monke. Closing.

**Comment by MGJerry** [comment]
Yeah, BTD6 automatically revert to a previous version of the saves whenever you edit stuff with the unpacker/packer.
From what I know, best you can do is turn off your internet connecttion, complete a game in offline mode (an Easy run on anymap should do), exit the game and turn on your internet again. Works every time.

**Comment by codeshaunted** [comment]
> Yeah, BTD6 automatically revert to a previous version of the saves whenever you edit stuff with the unpacker/packer.
> From what I know, best you can do is turn off your internet connecttion, complete a game in offline mode (an Easy run on anymap should do), exit the game and turn on your internet again. Works every time.

Does it do this if you don’t edit the save file at all when repacking? I’m thinking there must be some extra protection on micro transaction stuff…. I haven’t had this issue.

**Comment by Xioverze** [comment]
naw i just tried with a non ninja kiwi account, theres no extra protection its just cloud saves lol

Did what MGJerry mentioned, I now have double cash mode without paying a dime on my main account. I'm not even flagged lol.

**Comment by MGJerry** [comment]
> > Yeah, BTD6 automatically revert to a previous version of the saves whenever you edit stuff with the unpacker/packer.
> > From what I know, best you can do is turn off your internet connecttion, complete a game in offline mode (an Easy run on anymap should do), exit the game and turn on your internet again. Works every time.
> 
> Does it do this if you don’t edit the save file at all when repacking? I’m thinking there must be some extra protection on micro transaction stuff…. I haven’t had this issue.

Did this accidentally a few times, most of the time they stay the same size as when they are repacked (meaning the game assume nothing is out of the ordinary), while very rarely they are reverted to cloud saves.

And from what I've seen, saves are only reverted when they are linked to a ninjakiwi account, sometimes follow by a flag to the accounts after that. And the save usually only get revert if you add too much monkey money, xp & user rank,... There's probably a limit/threshold to how much a resource you can gain between checks, a lot of online game have this to prevent hacking in stuff (ex. from my past: The Battle Cats)

And like @Xioverze mentions above, non-ninjakiwi linked saves doesn't even get reverted, you can just use the save you just repacked and it works fine.
