### ISSUE TITLE
Bloons TD 6 - Game Resets Save

### ISSUE THREAD

**Issue by ghost** [codeshaunted/monke#2]
In Bloons TD 6 the game will reset the save back to the one stored in the cloud after a small amount of game play. Is there a way to fix this? This issue really makes this program essentially useless because the modded save will only stay modded while you aren't doing anything. As soon as you jump into a single player game, the game reloads your account, and the modified changes are gone.

**Comment by codeshaunted** [comment]
Don’t use cloud saves.

**Comment by ghost** [comment]
That isn't an option... Your data will always get saved to the cloud, at least when using an email.

**Comment by ghost** [comment]
This issue only happens when using modified profiles, if I use a friend's profile that isn't mine it works 100% fine and I have no issues. I assume it's an issue with the program and how its re-encrypting the save file.

**Comment by codeshaunted** [comment]
> This issue only happens when using modified profiles, if I use a friend's profile that isn't mine it works 100% fine and I have no issues. I assume it's an issue with the program and how its re-encrypting the save file.

You're saying it is loading the save though, just nuking it once you're in-game right? That would mean that the encryption is still the same and that my tool still works. Try not using a NinjaKiwi account.
