### ISSUE TITLE
Trying to replicate the save file format serialization/deserialization.

### ISSUE THREAD

**Issue by mriswithe** [codeshaunted/monke#4]
I am having trouble understanding what the format is here. I know the format comes out JSON, but I am trying to understand how you are unpacking it. 

To be clear, the problem is not with your code, it is with my understanding of the code! I just have a habit of rewriting stuff like this in python. Doesn't help that my C++ sucks and my crypto experience is limited to TLS/SSL certs for webservers.

# Bloons Save file
| Description               | Size     | Data Type |
|---------------------------|----------|-----------|
| Dummy Header              | 44       | Unknown   |
| password index            | 8        | uint64    |
| Password Salt             | 24       | char[24]  |
| Encrypted save data | The rest | ????      |

so is the order of operations:
1. read header (44 bytes)
2. read password index (8 bytes)
3. read password salt (24 bytes)
4. The rest of the file is encrypted, decrypt it
5. gunzip the decrypted data
6. You now have arrived at JSON

Or should 4/5 be switched?

If I am reading it right, it would be something like this:
```python
    def _read_file(self, file: Path) -> FILE_PIECES:
        with file.open("rb") as fp:
            # Unpack a char[44]
            header = struct.unpack("44s", fp.read(self._DUMMY_HEADER_LENGTH))[0]
            # Unpack a uint64
            password_index = struct.unpack("Q", fp.read(self._PASSWORD_INDEX_LENGTH))[0]
            # Unpack a char[24]
            salt = struct.unpack("24s", fp.read(self._SALT_LENGTH))[0]
            # The rest is encrypted data, just read the rest
            payload = fp.read()
        return header, password_index, salt, payload
```

I am not able to entirely replicate it and comparing values in memory with the debugger in CLion vs PyCharm is not apparently straight forward. Does this seem like the right direction?

**Comment by mriswithe** [comment]
https://github.com/mriswithe/pybtd6/blob/main/btd6_save_explorer/save_file.py

is my main `Save` class definition. Not much else exists in the repo atm

**Comment by codeshaunted** [comment]
You seem to be on the right track. Are you utilizing PBKDF2 to generate the decryuption key and IV? The real killer here would be differences in encryption implementation, I'm lucky that it worked so well with crypto++.

**Comment by mriswithe** [comment]
I thought I was but it seems like I am doing something wrong. The main issue I am having is even with debuggers running simultaneously in CLion and PyCharm the raw data and the like look entirely different and I am unsure why. 

This one is from CLion showing the dummy_header
![image](https://user-images.githubusercontent.com/1725647/146658507-e98f76f4-47eb-4ab1-8e9a-951e83df943c.png)

This one is from PyCharm showing the same dummy_header
![image](https://user-images.githubusercontent.com/1725647/146658537-288ec4ee-302b-4af5-95c4-e9caeec82271.png)

I usually would try and compare directly, but I am confused why they show the same data so differently.

**Comment by mriswithe** [comment]
I am using the std library hashlib in Python: https://docs.python.org/3/library/hashlib.html#hashlib.pbkdf2_hmac

Function signature:
```python
 hashlib.pbkdf2_hmac(hash_name, password, salt, iterations, dklen=None)
```
I am passing in: 
```python
{'dklen': 32, # Derived Key Length
 'hash_name': 'SHA1',
 'iterations': 10,
 'password': b'11',
 'salt': b'\xde;1\x87\xac\x0f\xa3\xda\xea\x9a\x9d\xe0R\xc0;+@k\xcd\xcc'
         b'\x11\xb8=\xf2'}
```

Going to try using the key derivation stuff that comes with Cryptodome (python library I am using) instead of making the Key with stdlib and trying to use it with Cryptodome.

**Comment by codeshaunted** [comment]
Yeah, I know nothing about hashlib, so you're on your own there. I at first implemented my pack/unpack methods in C# (for consistency with Bloons TD6, made in Unity), and then switched to C++ after. I remember there being some amount of friction when I was attempting to port it as certain configs either didn't exist or were different. If you have discord, my discord is averysumner#3787, I can discuss this with you in more depth there.

**Comment by mriswithe** [comment]
Sounds like a better place for the discussion! thanks!

**Comment by mriswithe** [comment]
To the future folk like me if you exist. This is what I was doing wrong. `hashlib.pbkdf2_hmac` returns a bytes object that is 32 bytes long (in this case). The first 16 bytes are the "Initialization Vector", the second 16 bytes are the "Key"

```python3
     @property
    def derived_key(self):
        return hashlib.pbkdf2_hmac(
            "SHA1",
            self._DEFAULT_PASSWORD,
            self.salt,
            self._HASH_ITERATIONS,
            self.dklen,
        )

    @property
    def dklen(self):
        return self._IV_LENGTH + self._KEY_LENGTH

    @property
    def key(self) -> bytes:
        return self.derived_key[16:]

    @property
    def init_vector(self) -> bytes:
        return self.derived_key[:16]

    @cached_property
    def cipher(self):
        return AES.new(self.key, AES.MODE_CBC, iv=self.init_vector)

    @cached_property
    def decrypted_save(self) -> bytes:
        return self.cipher.decrypt(self.encrypted_save)
```

The reason I didn't catch this was my misreading of the C++. I misread and didn't catch that there was pointer math going on here. when calling `decryptor.SetKeyWithIV` 
```cpp
  // derive key and iv from salt and password
  CryptoPP::byte derived_key[MONKE_KEY_LENGTH + MONKE_IV_LENGTH];
  CryptoPP::PKCS5_PBKDF2_HMAC<CryptoPP::SHA1> pbkdf2;
  pbkdf2.DeriveKey(derived_key, MONKE_KEY_LENGTH + MONKE_IV_LENGTH, 0,
                   (const CryptoPP::byte*)__password.data(), __password.size(),
                   (const CryptoPP::byte*)salt, sizeof(salt), MONKE_DERIVE_ITERATIONS, 0.0f);

  // set key and iv
  CryptoPP::CBC_Mode<CryptoPP::AES>::Decryption decryptor;
  decryptor.SetKeyWithIV(derived_key + MONKE_IV_LENGTH, MONKE_KEY_LENGTH, derived_key, MONKE_IV_LENGTH);
```

derived_key is a ptr to a char[32], and it passes in saying to go to the memory address 16 ahead of where the start of the char[32] is and says to read 16 bytes. Essentially the same thing that I am doing with `return self.derived_key[16:]`. 
Since I don't know the actual idea of what to do with the crypto stuff already, I didn't already know what to feed where.
