### ISSUE TITLE
Won't Compile in CMake GUI

### ISSUE THREAD

**Issue by KirboC** [codeshaunted/monke#6]
- Downloaded Source
- Created "build" folder within Source folder
- Opened CMake
- Selected Source folder and Build folder
- Configure selected as "Visual Studio 16 2019", left remaining boxes blank
- Used "default native compilers"
- Error in configuration process, project files may be invalid

ERRORS:
- BUILD_SHARED [BLANK BOX]
- BUILD_TESTING [BLANK BOX]
- CMAKE_CONFIGURATION_TYPES [Debug;Release;MinSizeRel;RelWithDebInfo]
- CMAKE_INSTALL_PREFIX [C:/Program Files (x86)/monke]

[CMakeOutput.log](https://github.com/codeshaunted/monke/files/8500395/CMakeOutput.log)

**Comment by codeshaunted** [comment]
You seem to have Visual Studio 2019 installed, can you try opening the project as a local folder in VS, then building it from there? Right click on the main CMakeLists.txt and hit build to build it in VS.

**Comment by KirboC** [comment]
I right clicked on CMakeLists.txt and there's no build option

**Comment by codeshaunted** [comment]
I don’t know what to tell you, it builds perfectly fine on fresh MSVC installs from my testing. That log also seems to be the wrong log file, I’d want the CMake build output.

**Comment by codeshaunted** [comment]
Closing this issue as it is stale.
