### ISSUE TITLE
Doesnt do anything

### ISSUE THREAD

**Issue by TheRealRebeg** [codeshaunted/monke#7]
Whenever i put "monke unpack "Profile.save" "New folder (2)" 11" It says that 'monke' isnt a "internal or external command,
operable program or batch file."

![Among Us](https://user-images.githubusercontent.com/104107668/164336905-c9102f66-6d1f-48c1-9bde-894f73e31db6.PNG)

**Comment by codeshaunted** [comment]
Unless you’ve installed it to your PATH, this will not work. You must build it and run it from the build folder.
